language: go
sudo: false
go:
  - "1.10"
before_install:
  - go get -u github.com/golang/dep/cmd/dep
install:
  - "$GOPATH/bin/dep ensure"
env:
  global:
    - NAME=clash
    - BINDIR=bin
script:
  - go test ./...
before_deploy: make -j releases
